### ISSUE TITLE
Could not load file or assembly TSS.UWP, Version=1.0.0.0

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.RaspberryPI.SampleUwpApp#15]
When running the `biz.dfch.CS.RaspberryPI.SampleUwpApp` on Raspberry Pi the following exception is thrown, if method for sending message to IoT Hub gets called.

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Could not load file or assembly 'TSS.UWP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at biz.dfch.CS.RaspberryPI.SampleUwpApp.Pages.CoffeeOverview..ctor() in C:\src\biz.dfch.CS.RaspberryPI.SampleUwpApp\src\biz.dfch.CS.RaspberryPI.SampleUwpApp\Pages\CoffeeOverview.xaml.cs:line 32

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'TSS.UWP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

```

**Comment by rufer7** [comment]
https://github.com/Azure/azure-iot-hub-vs-cs/issues/9

**Comment by rufer7** [comment]
Try to update NuGet packages

**Comment by rufer7** [comment]
https://blog.devmobile.co.nz/2019/05/08/windows-10-tpm-sas-token-expiry/

**Comment by rufer7** [comment]
https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-dotnet
